version: "3"

name: gitea

networks:
  gitea:
    external: false

secrets:
  postgres_passwd:
    file: ./postgres_password.passwd

services:
  # ----- Gitea Server
  # -------------------------
  server:
    image: gitea/gitea:latest
    depends_on:
      - db
    restart: always
    networks:
      - gitea
    ports:
      - "${GITEA_WEB_SERVER_PORT:-3000}:3000" # Web Server
      - "${GITEA_SSH_PORT:-222}:22" # SSH
    secrets:
      - postgres_passwd
    env_file:
      - ./server.env
      - ./db.env
    environment:
      GITEA__database__PASSWD: postgres_passwd
    volumes:
      - ./server_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  # ----- Gitea Database
  # -------------------------
  db:
    image: postgres:${POSTGRES_VERSION:-14}
    restart: always
    networks:
      - gitea
    secrets:
      - postgres_passwd
    env_file:
      - ./db.env
    environment:
      POSTGRES_PASSWORD: postgres_passwd
    volumes:
      - ./db_data:/var/lib/postgresql/data