version: "3"
name: gitea

networks:
  gitea:
    external: false

secrets:
  postgres_passwd:
    file: ./postgres_password.passwd
  gitea_web_cert:
    file: ./certificates/gitea_web_cert.pem
  gitea_web_key:
    file: ./certificates/gitea_web_key.pem

services:
  # ----- Gitea Server
  # -------------------------
  server:
    image: gitea/gitea:latest
    depends_on:
      - db
    restart: always
    networks:
      - gitea
    ports:
      - "3000:3000" # HTTP
      - "6443:443" # HTTPS
      - "622:22" # SSH
    secrets:
      - postgres_passwd
      - gitea_web_cert
      - gitea_web_key
    env_file:
      - ./server.env
      - ./db.env
    environment:
      GITEA__database__PASSWD: postgres_passwd
      GITEA__server__CERT_FILE: /run/secrets/gitea_web_cert
      GITEA__server__KEY_FILE: /run/secrets/gitea_web_key
    volumes:
      - ./server_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  # ----- Gitea Database
  # -------------------------
  db:
    image: postgres:${POSTGRES_VERSION:-14}
    restart: always
    networks:
      - gitea
    secrets:
      - postgres_passwd
    env_file:
      - ./db.env
    environment:
      POSTGRES_PASSWORD: postgres_passwd
    volumes:
      - ./db_data:/var/lib/postgresql