version: "3"
name: gitea

networks:
  gitea:
    external: false

secrets:
  postgres_passwd:
    file: ./secrets/passwords/gitea_runner_token.passwd
  gitea_web_cert:
    file: ./secrets/certificates/gitea_web_cert.pem
  gitea_web_key:
    file: ./secrets/certificates/gitea_web_key.pem
  gitea_runner_token:
    file: ./secrets/passwords/gitea_runner_token.passwd

services:
  # ----- Gitea Server
  server:
    image: gitea/gitea:latest
    depends_on:
      - db
    restart: always
    networks:
      - gitea
    ports:
      - "3000:3000" # HTTP
      - "6443:443" # HTTPS
      - "622:22" # SSH
    secrets:
      - postgres_passwd
      - gitea_web_cert
      - gitea_web_key
    env_file:
      - ./env/server.env
      - ./env/db.env
    environment:
      GITEA__database__PASSWD: postgres_passwd
      GITEA__server__CERT_FILE: /run/secrets/gitea_web_cert
      GITEA__server__KEY_FILE: /run/secrets/gitea_web_key
    volumes:
      - ./data/server_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # ----- Gitea Database
  db:
    image: postgres:14
    restart: always
    networks:
      - gitea
    secrets:
      - postgres_passwd
    env_file:
      - ./env/db.env
    environment:
      POSTGRES_PASSWORD: postgres_passwd
    volumes:
      - ./data/db_data:/var/lib/postgresql

  # ----- Gitea Runner
  runner:
    image: gitea/act_runner
    depends_on:
      - server
    restart: always
    networks:
      - gitea
    secrets:
      - gitea_runner_token
    env_file:
      - ./env/runner.env
      - ./env/server.env
    volumes:
      - ./data/runner_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITEA_RUNNER_REGISTRATION_TOKEN: gitea_runner_token
