version: "3"
name: arr

networks:
  arr:
    external: false

services:
  # ----- qBitTorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - arr
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      WEBUI_PORT: 8080
    volumes:
      - ./configs/qbittorrent:/config
      - /media/null/Raid0Array/Downloads:/downloads

  # ----- Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    
      - 7878:7878
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./configs/radarr:/config
      - /media/null/Raid0Array/Movies:/movies
      - /media/null/Raid0Array/Downloads:/downloads

  # ----- Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    networks:
      - arr
    ports:
      - 8686:8686
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./configs/lidarr:/config
      - /media/null/Raid0Array/Music:/music
      - /media/null/Raid0Array/Downloads:/downloads

  # ----- Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - arr
    ports:
      - 9696:9696
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./configs/prowlarr:/config