version: "3"
name: arr

networks:
  arr:
    external: false

services:
  # ----- qBitTorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      WEBUI_PORT: 8080
    volumes:
      - ./config:/config
      - /media/null/Raid0Array/Downloads:/downloads

  # ----- Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./config:/config
      - /media/null/Raid0Array/Movies:/movies
      - /media/null/Raid0Array/Downloads:/downloads